# -*- coding: utf-8 -*-
"""AIML-LAB-SHEET1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgGT1zINB88BfUJ2-V5pv51WnKsWfyqz
"""

#CREATING TUPLE WITH SINGLE ELEMENT

a=(5,)
print(a)
print(type(a))

#CREATING TUPLE WITH INTEGERS

a=(1,2,3,4,5)
print(a)

#CREATINGG TUPLE WITH FLOAT NUMBERS

b=(1.2,2.3,3.4,4.5)
print(b)

#CREATING TUPLE WITH STRINGS

c=("one","two","three","four","five")
print(c)

#CREATING TUPLE WITH MULTIPLE DATA TYPES

mix=(1,2,3,"one","two","three",6.7,7.9)
print(mix)

#ACCESSING ITEMS OF STRINGS

a=(1,2,3,4,"hello")
print(a[4])

#CREATE A DICTIONARY

a={
    "name":"joy",
    "age":20,
    "city":"kolkata"
}
print(a)

len(a)

type((a))

x=a.keys()
x

y=a.values()
y

z=a.items()
z

#SETS

set1={1,2,3,4,5}
print(set1)

#3 DUPLICATES NOT ALLOWED

set={1,2,3,4,5,1,2,3,4,5}
print(set)

len(set)

type(set)

def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())