# -*- coding: utf-8 -*-
"""AIML-LAB-SHEET2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cq-7XDhGUp3hjfXQ4PmbxUvlotnaeOh0
"""

import numpy as np
print(np.__version__)

A1=np.array([1,2,3])
print(A1)

type(A1)

A1.shape

A1.size

#2D ARRAY
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

type(A2)

A2.size

A2.shape

A2.ndim

#3D ARRAY
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

type(A3)

A3.size

A3.shape

A3.ndim

z1=np.zeros(3)
z1

#CHANGING DATA TYPE

z1=np.zeros(3,dtype=int)
z1

z1.shape

z1.size

z1.ndim

type(z1)

z2=np.zeros((3,4))
z2

z2=np.zeros((3,4),dtype=int)
z2

type(z2)

z2.shape

z2.size

z2.ndim

z3=np.zeros((2,3,4))
z3

z3=np.zeros((2,3,4),dtype=int)
z3

z3.shape

z3.size

z3.ndim

type(z3)

#1D 0NES ARRAY
a1=np.ones(3)
a1

a1=np.ones(3,dtype=int)
a1
print(type(a1))
print(a1.shape)
print(a1.size)
print(a1.ndim)

#2D ONES ARRAY

a2=np.ones([3,4])
a2

a2=np.ones([3,4],dtype=int)
a2

print(type(a2))
print(a2.shape)
print(a2.size)
print(a2.ndim)

#3D ONES ARRAY

a3=np.ones([4,2,3])
a3

a3=np.ones([4,2,3],dtype=int)
a3

print(type(a3))
print(a3.shape)
print(a3.size)
print(a3.ndim)

#1D FULL ARRAY
#EASY TO NAVIGATE

f1=np.full(3,9)
print(f1)

f1=np.full(3,9,dtype=int)
print(f1)
print(type(f1))
print(f1.shape)
print(f1.size)
print(f1.ndim)

#2D FULL ARRAY

f2=np.full([2,3],9)
print(f2)

f2=np.full([2,3],9,dtype=int)
print(f2)
print(type(f2))
print(f2.shape)
print(f2.size)
print(f2.ndim)

#3D FULL ARRAY

f3=np.full([4,2,3],9)
print(f3)

f3=np.full([4,2,3],9,dtype=int)
print(f3)
print(type(f3))
print(f3.shape)
print(f3.size)
print(f3.ndim)

#ADD

a=np.array([1,2,3])
b=np.array([1,2,3])

add=np.add(a,b)
add

#SUBTRACT

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.subtract(a,b)
sub

#MULTIPLY

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.multiply(a,b)
sub

#DIVIDE

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.divide(a,b)
sub

#MOD

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.mod(a,b)
sub

#POWER

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.power(a,b)
sub